package arduino;

import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.util.Enumeration;
import javax.swing.JOptionPane;

//************************************************************//
//          CASU - Controle e Automacao Submarina             //
//Eduardo Luis dos Santos                                     //
//Erico de Castro Rodrigues                                   //
//Joel Magalhaes de Souza                                     //
//Lucas Emanuel do Rego                                       //
//Wesley Okumura Shenci                                       //
//************************************************************//
public class frmPrincipal extends javax.swing.JFrame {
    
    //Variavel usada para verificar inico de comando
    private static final byte STX = (byte) 255;
    
    //Variavel que define o estado ligado
    private static final byte ON = 1;
    //Variavel que define o estado desligado
    private static final byte OFF = 0;
    
    //Variaveis refente aos servo motores
    private static final byte SERVO1 = 10;
    private static final byte SERVO2 = 11;
    private static final byte SERVO_EMBOLO = 12;
    
    //Variavel referente ao motor DC
    private static final byte MOTOR = 9;
    
    //Para a comunicacao serial foi usada a biblioteca RXTXcomm.jar    
    //Variaveis de Conexao
    private OutputStream output = null;
    private BufferedReader input;
    SerialPort serialPort;
    private final String porta="COM4";//COM4 4 Porta do modulo APC220
    private static final int timeOut = 2000; //2 segundos
    private static final int dataRate = 9600;  
    //21.2 peso lastro ajuste fino
    
    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal() {
        initComponents();
        iniciarConexao();
    }
    
    //Metodo para inicio de comunicacao com o Arduino
    public void iniciarConexao(){
        CommPortIdentifier portaId = null;
        Enumeration portaEnum = CommPortIdentifier.getPortIdentifiers();
        
        while(portaEnum.hasMoreElements()){
            CommPortIdentifier atualPortaId =(CommPortIdentifier) portaEnum.nextElement();
            if(porta.equals(atualPortaId.getName())){
                portaId=atualPortaId;
                break;
            }
        }
        if(portaId == null){
            mostrarErro("Não se pode conectar a porta");
            //System.exit(ERROR);
        }
        
        try{
            serialPort = (SerialPort) portaId.open(this.getClass().getName(), timeOut);
            //parametros da porta serial
            
            serialPort.setSerialPortParams(dataRate, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
            output = serialPort.getOutputStream();
            input = new BufferedReader(new InputStreamReader(serialPort.getInputStream()));
        }catch(Exception e){
            mostrarErro(e.getMessage());
            System.exit(ERROR);
        }
    }
    
    //Metodo usado para enviar dados ao Arduino
    private void enviarDados(byte[] dados){
        try{            
            output.write(dados);         
        }catch(Exception e){
            mostrarErro("Erro");
            e.printStackTrace();
            System.exit(ERROR);
        }
    }
    
    public void mostrarErro(String mensagem){
        JOptionPane.showMessageDialog(this, mensagem,"ERRO",JOptionPane.ERROR_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_ligarMotor = new javax.swing.JButton();
        btn_desligarMotor = new javax.swing.JButton();
        lbl = new javax.swing.JLabel();
        pot_servo2 = new javax.swing.JSlider();
        pot_servo1 = new javax.swing.JSlider();
        jLabel2 = new javax.swing.JLabel();
        btn_emergir = new javax.swing.JButton();
        btn_submergir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASU - Protótipo");

        btn_ligarMotor.setBackground(new java.awt.Color(51, 255, 0));
        btn_ligarMotor.setText("ON");
        btn_ligarMotor.setName("btn_ligarMotor"); // NOI18N
        btn_ligarMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ligarMotorActionPerformed(evt);
            }
        });

        btn_desligarMotor.setBackground(new java.awt.Color(255, 0, 0));
        btn_desligarMotor.setText("OFF");
        btn_desligarMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desligarMotorActionPerformed(evt);
            }
        });

        lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl.setText("Motor:");

        pot_servo2.setMajorTickSpacing(10);
        pot_servo2.setMaximum(180);
        pot_servo2.setMinorTickSpacing(5);
        pot_servo2.setOrientation(javax.swing.JSlider.VERTICAL);
        pot_servo2.setPaintLabels(true);
        pot_servo2.setPaintTicks(true);
        pot_servo2.setToolTipText("");
        pot_servo2.setValue(90);
        pot_servo2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pot_servo2StateChanged(evt);
            }
        });

        pot_servo1.setMajorTickSpacing(10);
        pot_servo1.setMaximum(180);
        pot_servo1.setMinorTickSpacing(5);
        pot_servo1.setOrientation(javax.swing.JSlider.VERTICAL);
        pot_servo1.setPaintLabels(true);
        pot_servo1.setPaintTicks(true);
        pot_servo1.setValue(90);
        pot_servo1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pot_servo1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pot_servo1StateChanged(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arduino/logo.png"))); // NOI18N

        btn_emergir.setText("Emergir");
        btn_emergir.setName("btn_emergir"); // NOI18N
        btn_emergir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_emergirActionPerformed(evt);
            }
        });

        btn_submergir.setText("Submergir");
        btn_submergir.setName("btn_submergir"); // NOI18N
        btn_submergir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submergirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pot_servo1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl)
                                .addGap(156, 156, 156))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_ligarMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_desligarMotor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_emergir, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_submergir)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(pot_servo2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pot_servo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(77, 77, 77)
                        .addComponent(lbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ligarMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_desligarMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_emergir, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                            .addComponent(btn_submergir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pot_servo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btn_emergir.getAccessibleContext().setAccessibleName("btn_emergir");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ligarMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ligarMotorActionPerformed
        byte[] dados = new byte[3];
        dados[0]=STX;
        dados[1]=MOTOR;
        dados[2]=ON;
        enviarDados(dados);
    }//GEN-LAST:event_btn_ligarMotorActionPerformed

    private void btn_desligarMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desligarMotorActionPerformed
        byte[] dados = new byte[3];
        dados[0]=STX;
        dados[1]=MOTOR;
        dados[2]=OFF;
        enviarDados(dados);
    }//GEN-LAST:event_btn_desligarMotorActionPerformed

    private void pot_servo1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pot_servo1StateChanged
        byte[] dados = new byte[3];
        dados[0]=STX;
        dados[1]=SERVO1;
        dados[2]=(byte)pot_servo1.getValue();
        enviarDados(dados);
    }//GEN-LAST:event_pot_servo1StateChanged

    private void pot_servo2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pot_servo2StateChanged
        byte[] dados = new byte[3];
        dados[0]=STX;
        dados[1]=SERVO2;
        dados[2]=(byte)pot_servo2.getValue();
        enviarDados(dados);
    }//GEN-LAST:event_pot_servo2StateChanged

    private void btn_emergirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_emergirActionPerformed
        byte[] dados = new byte[3];                
        dados[0]=STX;
        dados[1]=SERVO_EMBOLO;
        dados[2]=(byte)25;
        enviarDados(dados);
    }//GEN-LAST:event_btn_emergirActionPerformed

    private void btn_submergirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submergirActionPerformed
        byte[] dados = new byte[3];
        dados[0]=STX;
        dados[1]=SERVO_EMBOLO;
        dados[2]=(byte)155;
        enviarDados(dados);
    }//GEN-LAST:event_btn_submergirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desligarMotor;
    private javax.swing.JButton btn_emergir;
    private javax.swing.JButton btn_ligarMotor;
    private javax.swing.JButton btn_submergir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl;
    private javax.swing.JSlider pot_servo1;
    private javax.swing.JSlider pot_servo2;
    // End of variables declaration//GEN-END:variables
}
